package cz.arouskova.autoscaler.core;

import cz.arouskova.autoscaler.instance.InstanceSnapshot;

import java.util.List;

/**
 * Immutable point-in-time view of the simulation state, produced by
 * {@link cz.arouskova.autoscaler.metrics.MetricsCollector} once per tick
 * and consumed by the UI on the JavaFX thread.
 * <p>
 * All list components are defensively copied via {@link List#copyOf(java.util.Collection)}
 * so the snapshot is safe to publish across threads and cannot be mutated
 * by holders of the original collections.
 *
 * @param tick                  monotonic tick index at which the snapshot was taken
 * @param throughput            requests per second over the latest 1-second window
 * @param avgLatency            average request latency in ms during the current tick
 * @param avgQueueLength        average queue length across all ACTIVE instances
 * @param droppedCount          total number of requests dropped since simulation start
 * @param dropRate              ratio of dropped to submitted requests in this tick
 * @param utilization           fraction of busy workers across all ACTIVE instances (0..1)
 * @param activeInstanceCount   number of ACTIVE instances (drives autoscaler decisions)
 * @param requestsThisTick      number of requests generated by the traffic profile during this tick
 * @param latencyHistory        rolling history of {@code avgLatency} values
 * @param throughputHistory     rolling history of {@code throughput} values
 * @param instanceCountHistory  rolling history of {@code activeInstanceCount} values
 * @param instances             all non-terminated instances (ACTIVE + DRAINING) for the UI table
 */
public record Snapshot(
        long tick,
        double throughput,
        double avgLatency,
        double avgQueueLength,
        int droppedCount,
        double dropRate,
        double utilization,
        int activeInstanceCount,
        int requestsThisTick,
        List<Double> latencyHistory,
        List<Double> throughputHistory,
        List<Double> instanceCountHistory,
        List<InstanceSnapshot> instances
) {
    public Snapshot {
        latencyHistory = List.copyOf(latencyHistory);
        throughputHistory = List.copyOf(throughputHistory);
        instanceCountHistory = List.copyOf(instanceCountHistory);
        instances = List.copyOf(instances);
    }
}
